const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { World, SIZE, names } = require('./world.js');

async function main() {
  const empty = new World();
  empty.set(4, 2, 4, 3);
  const ray = empty.raycast({x:4.5,y:2.5,z:8.5},{x:0,y:0,z:-1});
  assert.equal(ray.z, 4); assert.deepEqual(ray.normal,{x:0,y:0,z:1});
  assert.equal(empty.raycast({x:4.5,y:2.5,z:14.5},{x:0,y:0,z:-1}),null);
  assert.equal(empty.raycast({x:4.5,y:2.5,z:8.5},{x:0,y:0,z:0}),null);
  assert.equal(empty.collides({x:4.5,y:2,z:4.5}),true);
  assert.equal(empty.collides({x:4.5,y:3,z:4.5}),false);
  assert.equal(empty.intersectsPlayer(4,3,4,{x:4.5,y:3,z:4.5}),true);
  assert.equal(empty.intersectsPlayer(6,3,4,{x:4.5,y:3,z:4.5}),false);
  const world = new World(); world.generate();
  assert.equal(world.collides({x:34.5,y:9.01,z:42.5}),false);
  assert.equal(world.get(34,8,42),1);
  assert.equal(SIZE,80);assert.equal(names.length-1,9);
  assert.ok(world.surface(79,79)>0,'Terrain reaches the enlarged boundary');
  assert.equal(world.collides({x:79.8,y:31,z:79.5}),true,'Outer world boundary remains solid');
  assert.equal(world.collides({x:64.5,y:31,z:64.5}),false,'Old boundary no longer blocks movement');
  empty.set(79,10,79,9);
  assert.equal(empty.raycast({x:77.5,y:10.5,z:79.5},{x:1,y:0,z:0}).id,9);
  console.log('PASS: raycast, reach limit, axis-aligned rays, collisions, spawn and placement protection');

  const {chromium} = require('C:/Users/PC/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
  const browser = await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:900}});
    const errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
    const requests=[];page.on('request',r=>requests.push(r.url()));
    // Test the documented keyboard alternative deterministically in headless mode.
    await page.addInitScript(()=>{HTMLCanvasElement.prototype.requestPointerLock=undefined;});
    await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);
    await page.waitForFunction(()=>window.voxelGame?.inspect().ready);
    await page.screenshot({path:path.join(__dirname,'preview-menu.png')});
    assert.equal(await page.locator('#fatal').isVisible(),false);
    await page.locator('#play').click();
    await page.waitForFunction(()=>window.voxelGame.inspect().grounded);
    let state=await page.evaluate(()=>window.voxelGame.inspect());
    assert.equal(state.active,true);assert.equal(state.fallback,true);
    assert.equal(state.worldSize,80);assert.equal(state.chunks,25);assert.equal(state.blockTypes,9);
    assert.equal(await page.locator('#hotbar .slot').count(),9);
    assert.equal(await page.locator('#coordinates').isVisible(),true);
    const cloudsBefore=state.clouds;
    const positionBefore=await page.locator('#position-value').textContent();
    const y=state.player.y;
    await page.keyboard.press('Space');await page.waitForTimeout(180);
    state=await page.evaluate(()=>window.voxelGame.inspect());assert.ok(state.player.y>y+.3,'Jump lifts player');
    await page.waitForFunction(()=>window.voxelGame.inspect().grounded);
    const before=await page.evaluate(()=>window.voxelGame.inspect().player);
    await page.keyboard.down('KeyW');await page.waitForTimeout(400);await page.keyboard.up('KeyW');
    const after=await page.evaluate(()=>window.voxelGame.inspect().player);
    assert.ok(Math.hypot(after.x-before.x,after.z-before.z)>.6,'W moves player');
    assert.notEqual(await page.locator('#position-value').textContent(),positionBefore);
    const positionCheck=await page.evaluate(()=>({p:window.voxelGame.inspect().player,text:document.getElementById('position-value').textContent}));
    assert.equal(positionCheck.text,`X: ${positionCheck.p.x.toFixed(1)} / Y: ${positionCheck.p.y.toFixed(1)} / Z: ${positionCheck.p.z.toFixed(1)}`);
    await page.keyboard.press('Digit7');
    assert.equal(await page.evaluate(()=>window.voxelGame.inspect().selected),7);
    await page.keyboard.down('ArrowDown');await page.waitForTimeout(560);await page.keyboard.up('ArrowDown');
    await page.waitForFunction(()=>!!window.voxelGame.inspect().hit);
    const blocks=await page.evaluate(()=>window.voxelGame.inspect().blocks);
    await page.keyboard.press('KeyQ');
    assert.equal(await page.evaluate(()=>window.voxelGame.inspect().blocks),blocks-1);
    await page.waitForTimeout(180);await page.keyboard.press('KeyE');
    assert.equal(await page.evaluate(()=>window.voxelGame.inspect().blocks),blocks);
    for(const id of [8,9]){
      await page.keyboard.press(`Digit${id}`);
      assert.equal(await page.evaluate(()=>window.voxelGame.inspect().selected),id);
      assert.equal(await page.locator('#selected-name').textContent(),names[id]);
      await page.waitForTimeout(180);await page.keyboard.press('KeyQ');
      assert.equal(await page.evaluate(()=>window.voxelGame.inspect().blocks),blocks-1);
      await page.waitForTimeout(180);await page.keyboard.press('KeyE');
      assert.equal(await page.evaluate(()=>window.voxelGame.inspect().blocks),blocks);
      assert.equal(await page.evaluate(()=>window.voxelGame.inspect().hit.id),id,'New block can be placed and targeted');
    }
    await page.mouse.wheel(0,100);
    await page.waitForFunction(()=>window.voxelGame.inspect().selected===1);
    await page.mouse.wheel(0,-100);
    await page.waitForFunction(()=>window.voxelGame.inspect().selected===9);
    const cloudsAfter=await page.evaluate(()=>window.voxelGame.inspect().clouds);
    assert.equal(cloudsAfter.count,24);
    assert.ok(cloudsAfter.positions[0].x-cloudsBefore.positions[0].x>.3,'Clouds drift over time');
    console.log('PASS: 80x80 map, 25 chunks, nine block slots, new materials placed/mined, wheel wrapping, live XYZ and moving clouds');
    await page.screenshot({path:path.join(__dirname,'preview-game.png')});
    const flightStartY=await page.evaluate(()=>window.voxelGame.inspect().player.y);
    await page.keyboard.press('KeyF');
    assert.equal(await page.evaluate(()=>window.voxelGame.inspect().flying),true);
    assert.match(await page.locator('#movement-mode').textContent(),/Latanie/);
    await page.keyboard.down('Space');await page.waitForTimeout(250);await page.keyboard.up('Space');
    const flyingY=await page.evaluate(()=>window.voxelGame.inspect().player.y);
    assert.ok(flyingY>flightStartY+1,'Space ascends in flight');
    await page.waitForTimeout(150);
    assert.ok(Math.abs(await page.evaluate(()=>window.voxelGame.inspect().player.y)-flyingY)<.1,'Flight hovers');
    await page.keyboard.down('KeyC');await page.waitForTimeout(150);await page.keyboard.up('KeyC');
    assert.ok(await page.evaluate(()=>window.voxelGame.inspect().player.y)<flyingY-.5,'C descends');
    await page.keyboard.press('KeyF');
    assert.equal(await page.evaluate(()=>window.voxelGame.inspect().flying),false);
    await page.waitForFunction(()=>window.voxelGame.inspect().grounded);
    console.log('PASS: F toggles flight, Space rises, hover, C descends and flight UI updates');
    await page.keyboard.press('Escape');assert.equal(await page.locator('#menu').isVisible(),true);
    await page.locator('#play').click();assert.equal(await page.evaluate(()=>window.voxelGame.inspect().active),true);
    await page.keyboard.press('Escape');
    await page.locator('#respawn').click();
    assert.equal(await page.evaluate(()=>window.voxelGame.inspect().player.x),34.5);
    await page.keyboard.press('KeyF');
    await page.keyboard.down('Space');await page.waitForTimeout(2400);await page.keyboard.up('Space');
    await page.keyboard.down('ArrowUp');await page.waitForTimeout(220);await page.keyboard.up('ArrowUp');
    await page.screenshot({path:path.join(__dirname,'preview-expanded-world.png')});
    await page.setViewportSize({width:390,height:844});
    const bar=await page.locator('#hotbar').boundingBox();
    assert.ok(bar.x>=0&&bar.x+bar.width<=390,'Nine-block hotbar fits narrow viewport');
    await page.screenshot({path:path.join(__dirname,'preview-narrow-game.png')});
    await page.keyboard.press('Escape');
    await page.setViewportSize({width:800,height:600});
    assert.ok(await page.locator('#play').isVisible());
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.screenshot({path:path.join(__dirname,'preview-controls.png')});
    assert.deepEqual(errors,[],'No page or WebGL errors');
    assert.equal(requests.some(url=>/^https?:/.test(url)),false,'No internet needed');
    console.log('PASS: 3D rendering, start/pause/resume, fallback, jump, movement, block selection, mining, placing, respawn, resized UI, offline assets');
    console.log(JSON.stringify(await page.evaluate(()=>{const s=window.voxelGame.inspect();return{worldSize:s.worldSize,blockTypes:s.blockTypes,clouds:s.clouds.count,chunks:s.chunks,drawCalls:s.drawCalls,triangles:s.triangles};})));
    const normal=await browser.newPage({viewport:{width:1280,height:800}});
    await normal.goto(pathToFileURL(path.join(__dirname,'index.html')).href);
    await normal.waitForFunction(()=>window.voxelGame?.inspect().ready);
    await normal.locator('#play').click();
    await normal.waitForFunction(()=>document.pointerLockElement||window.voxelGame.inspect().fallback);
    console.log('Pointer lock result:',await normal.evaluate(()=>({locked:!!document.pointerLockElement,fallback:window.voxelGame.inspect().fallback})));
  } finally {await browser.close();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
